### ISSUE TITLE
Bug in __construct()

### ISSUE THREAD

**Issue by lexo13** [jimschubert/intellij-swagger-codegen#14]
Hi,

https://api-docs.beezup.com/swagger.json

perhaps a bug in constructor variables assignation . 
default generated code is by example in camelCase (bug also in snake_case):

`$this->container['marketplaceTechnicalCode'] = isset($data['marketplaceTechnicalCode']) ? $data['marketplaceTechnicalCode'] : null;`

instead of :

`$this->container['marketplaceTechnicalCode'] = isset($data[self::attributeMap()['marketplaceTechnicalCode']]) ? $data[self::attributeMap()['marketplaceTechnicalCode']] : null;`

You must use attributeMap to find the good variable name.

**Comment by jimschubert** [comment]
@lexo13 Thanks for reporting this issue. Sorry that I'm just now seeing this issue. I'm working on buying a house and haven't had free time in the evenings/weekends for a couple of months.

This is an issue or concern with Swagger Codegen rather than this project, which is just a dynamically built UI wrapper on top of Swagger Codegen.

I've just pushed a new version of the plugin which bumps the Swagger Codegen version being used up to 2.3.1. I've generated against the linked swagger.json, but I don't see code similar to the code you've documented above. I'm also not familiar enough with PHP to comment one way or the other about how that generator works (I maintain C#/Kotlin/Scala generators, and contribute to various tooling).

Try this out again once the 2.3.1 update is approved by Jetbrains and lands in the plugin repository as an available update. If you continue to see problems with the generator you're using, open an issue at https://github.com/swagger-api/swagger-codegen.

One thing you may also consider is customizing the template for your targeted generator. To do this, you'd want to pull the templates from the swagger-codegen repo locally, modify them to suite your needs, and reference them as a custom template.

For example:

```
mkdir -p ~/temp/issues/intellij-swagger-codegen
git clone git@github.com:swagger-api/swagger-codegen.git
cd swagger-codegen/
git checkout v2.3.1
cd swagger-codegen/modules/swagger-codegen/src/main/resources/php
vim model_generic.mustache +164
```

From here, you'll want to make your edits and save.

Once you're done, you can reference the customized template directly in the 'Template Directory' option of 'Generator Settings':
![image](https://user-images.githubusercontent.com/109659/37885480-71e08620-3083-11e8-9654-77e0d10a7aaf.png)

I'm going to close this issue since it's not related to the intellij plugin but to a dependency. If neither of the suggestions above work, please open an issue on the Swagger Codegen repo.
