### ISSUE TITLE
When typing an output directory, subsequent paths are created as typed

### ISSUE THREAD

**Issue by RELnemtzov** [jimschubert/intellij-swagger-codegen#16]
Using v1.0.0 on Intellij IDEA 2018.1 in Linux Mint 18.3, but the issue existed on 2017.3 as well.
Suppose I want to output to `/tmp/swagger` then **all** of the following directories are created:
`/tmp/s`
`/tmp/sw`
`/tmp/swa`
`/tmp/swag`
`/tmp/swagg`
`/tmp/swagge`
`/tmp/swagger`

**Comment by jimschubert** [comment]
Thanks for reporting this. I assume I'm doing a mkdir on UI update rather than on clicking OK or something here. Unfortunately, I'm going to be busy for the next 3 or 4 days (at least) so it may be a bit before I get around to looking at this.

I'm going to tag as `help wanted` and see if someone wants to pick it up since I think it'll be relatively simple.

**Comment by jimschubert** [comment]
@RELnemtzov I'm unable to repro this on Mac or Linux Mint. Is there any additional information you can provide?

I've tested 2017.3  with plugin versions v0.1.0 and v1.0.0 and 2018.1 with v1.0.0.

**Comment by jimschubert** [comment]
I'm going to close this, as I can't repro and haven't heard back. If you're still having the issue, please reopen.
