### ISSUE TITLE
How can I change text header and text links of left side of html2 version

### ISSUE THREAD

**Issue by NabiKAZ** [jimschubert/intellij-swagger-codegen#8]
Hi,

How can I change text header and text links in position 1 and 2 specified in this picture:

![image](https://cloud.githubusercontent.com/assets/246721/26275748/645d5568-3d7d-11e7-980e-dbd9c4575584.png)

Thanks

**Comment by jimschubert** [comment]
@NabiKAZ this plugin builds up much of the settings you can used with Swagger Codegen dynamically.

In the html2  generator's "Generator Settings" tab, you can specify a template directory to use modified mustache templates from the swagger codegen project. I haven't tested this with the plugin, but since it's essentially just a pass-through to swagger-codegen, it should just work.

To customize the templates for html2 generation, here are the steps.

1. Clone or download `swagger-codegen`
   - `git clone git@github.com:swagger-api/swagger-codegen.git`
   - `git checkout v2.2.2`
   - NOTE: above version must match version from plugin (Code -> Swagger -> Codegen Version)
2. Copy all files from `src/main/resources/htmlDocs2` into a separate directory (you'll point to this directory later during generation)
3. Modify the .mustache files as desired. Don't change the filenames or the generator may not work correctly.
4. Refer to [StaticHtml2Generator.java](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/StaticHtml2Generator.java) if you have questions about any variables used in the templates.
5. When you generate, specify the new directory where you copied the sources in step 2.

Let me know if that helps.

**Comment by NabiKAZ** [comment]
Thanks for your reply.
You can see: https://github.com/swagger-api/swagger-codegen/issues/5680

**Comment by jimschubert** [comment]
Ah, I see now. I misunderstood. I thought you wanted to change the appearance rather than the text that gets modified by Swagger Codegen.

**Comment by jimschubert** [comment]
I'm going to close this since an appropriate response of customized templates was provided in the linked issue. Let me know if there are additional questions related to this plugin.
